//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "block")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub version: i32,
    #[sea_orm(column_type = "JsonBinary")]
    pub content: Json,
    #[sea_orm(column_type = "Float")]
    pub order: f32,
    pub note_id: Uuid,
    #[sea_orm(
        belongs_to,
        from = "note_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub note: HasOne<super::note::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
