//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.19

use super::sea_orm_active_enums::OauthProvider;
use super::sea_orm_active_enums::TokenType;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "oauth2")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub user_id: Uuid,
    pub oauth_provider: OauthProvider,
    pub oauth_type: TokenType,
    pub expires_at: Option<DateTime>,
    #[sea_orm(column_type = "JsonBinary")]
    pub scopes: Json,
    pub provider_user_id: String,
    pub refresh_token: Option<String>,
    pub access_token: String,
    #[sea_orm(
        belongs_to,
        from = "user_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub user: HasOne<super::user::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
