//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.19

pub use super::block::Entity as Block;
pub use super::note::Entity as Note;
pub use super::oauth2::Entity as Oauth2;
pub use super::password::Entity as Password;
pub use super::refresh_tokens::Entity as RefreshTokens;
pub use super::user::Entity as User;
