//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};
use utoipa::ToSchema;

#[derive(
    Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize, ToSchema,
)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "oauth_provider")]
#[serde(rename_all = "lowercase")]
pub enum OauthProvider {
    #[sea_orm(string_value = "google")]
    Google,
    #[sea_orm(string_value = "facebook")]
    Facebook,
    #[sea_orm(string_value = "twitter")]
    Twitter,
    #[sea_orm(string_value = "github")]
    Github,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "token_type")]
pub enum TokenType {
    #[sea_orm(string_value = "bearer")]
    Bearer,
    #[sea_orm(string_value = "mac")]
    Mac,
    #[sea_orm(string_value = "extension")]
    Extension,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "user_type")]
pub enum UserType {
    #[sea_orm(string_value = "admin")]
    Admin,
    #[sea_orm(string_value = "regular")]
    Regular,
    #[sea_orm(string_value = "guest")]
    Guest,
}
