//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.19

use super::sea_orm_active_enums::UserType;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "user")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(unique)]
    pub username: String,
    #[sea_orm(unique)]
    pub email: String,
    pub user_type: UserType,
    #[sea_orm(has_many)]
    pub notes: HasMany<super::note::Entity>,
    #[sea_orm(has_many)]
    pub oauth2s: HasMany<super::oauth2::Entity>,
    #[sea_orm(has_one)]
    pub password: HasOne<super::password::Entity>,
    #[sea_orm(has_many)]
    pub refresh_tokens: HasMany<super::refresh_tokens::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
